// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { GetOrderOrderSnGetData, GetOrderOrderSnGetError, GetOrderOrderSnGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Order
 */
export const getOrderOrderSnGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetOrderOrderSnGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOrderOrderSnGetResponse, GetOrderOrderSnGetError, ThrowOnError>({
        ...options,
        url: '/order_sn'
    });
};