// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type OrderModelResponse = {
    find_state: number;
    order_sn?: (string | null);
    shop_name?: (string | null);
    avatar?: (string | null);
    status_msg?: (string | null);
    bonus_amount?: (string | null);
    send_time_format?: (string | null);
    buyer_nick?: (string | null);
    wechat_nick?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetOrderOrderSnGetData = {
    query: {
        order_sn: string;
    };
};

export type GetOrderOrderSnGetResponse = (OrderModelResponse);

export type GetOrderOrderSnGetError = (HTTPValidationError);